// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8ttI4fUqDGWurHX6JvXZzbnfRostqq9c',
    appId: '1:566643753143:web:50b4296b5e208ed00f4d32',
    messagingSenderId: '566643753143',
    projectId: 'gastosapp-bcedf',
    authDomain: 'gastosapp-bcedf.firebaseapp.com',
    storageBucket: 'gastosapp-bcedf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuRbcA9awK6i045rR0jH_zMQqYvQaoICk',
    appId: '1:566643753143:android:277625f1868c83070f4d32',
    messagingSenderId: '566643753143',
    projectId: 'gastosapp-bcedf',
    storageBucket: 'gastosapp-bcedf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuf2amdKtN6eJ0rFot5MupzO48vmpvIag',
    appId: '1:566643753143:ios:d8a895073f52a71e0f4d32',
    messagingSenderId: '566643753143',
    projectId: 'gastosapp-bcedf',
    storageBucket: 'gastosapp-bcedf.appspot.com',
    iosBundleId: 'com.example.sitegastos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuf2amdKtN6eJ0rFot5MupzO48vmpvIag',
    appId: '1:566643753143:ios:af73f18ce7cc6b370f4d32',
    messagingSenderId: '566643753143',
    projectId: 'gastosapp-bcedf',
    storageBucket: 'gastosapp-bcedf.appspot.com',
    iosBundleId: 'com.example.sitegastos.RunnerTests',
  );
}
